dist: trusty
language: node_js

node_js:
  - "4"
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

addons:
  chrome: beta

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - git lfs pull

  # Install npmv3 because of postinstall bugs in npmv2:
  # See https://github.com/FormidableLabs/victory/issues/98
  - npm install -g npm@3

  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm --version
  - node_modules/.bin/builder run check-ci
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then npm run loki-ci; fi'

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - node_modules/.bin/builder run build
